### ISSUE TITLE
fix: stack-resolver diagnostic logger crashes on every param-store failure, masking the real error and 500ing provision status

### ISSUE THREAD

**Issue by birme** [Eyevinn/open-videocore#437]
## Summary

On the `ovctest` instance, every parameter-store refresh currently crashes the diagnostic logger instead of logging, which (a) 500s `GET /api/v1/provision/:name`, (b) forces every request onto the in-memory/no-storage fallback (so assets, jobs, and pipelines all appear empty even though the provisioned CouchDB/MinIO stack is presumably intact), and (c) breaks the Encore autoscaler's Redis URL resolution. The real, underlying param-store failure is never visible because the crash happens before it can be logged.

## Evidence (ovctest instance logs)

```
TypeError: this[writeSym] is not a function
  at Object.LOG [as error] (pino/lib/tools.js:69:21)
  at withRetry (dist/services/param-store.js:216:26)
  at async WorkspaceStackResolver.resolve (dist/services/workspace-stack.js:323:30)
  ...
msg: "stack resolver: parameter-store refresh failed; serving fallback resolution"
fallback: "in-memory (no object storage)"
```

Same crash signature also fires from:
- `GET /api/v1/provision/ovctest` → unhandled, returns `500` (`routes/provision.js:915`)
- `reconcileScaler` → `resolveStackRedisUrl` (`main.js:912`/`533`) → `"encore-scaler: failed to resolve Redis URL from parameter store"`

`GET /api/v1/assets`, `/api/v1/jobs`, `/api/v1/pipelines` all return `200` with empty results — consistent with every request being served from the in-memory fallback rather than the real stack.

## Root cause

`src/services/param-store.ts` (introduced by #431 / #433):

```ts
const diag: ResolvedParamStoreLogger = { ...NOOP_DIAG_LOG, ...config.log };
```

`config.log` is `app.log` — a live Fastify/pino logger instance (wired in `main.ts` wherever `paramStoreFromEnv(..., { log: app.log })` is called). Spreading `config.log` copies its methods (`info`/`warn`/`debug`/`error`) as plain function references, detached from `this`. Pino's internal per-level `LOG` function depends on `this[writeSym]`, which only exists on the real logger instance — once detached, **every call to `diag.error/warn/debug/info` throws instead of logging.**

This means:
1. The actual param-store failure reason is never observable — the crash happens before the message is written.
2. Call sites that catch-and-fall-back (most of them) silently degrade to `in-memory (no object storage)` on *every* request, since the resolve path can never complete without hitting the broken logger.
3. `routes/provision.js:915` does not catch the throw, so `GET /api/v1/provision/:name` 500s outright.

## Proposed fix

Don't spread a pino/logger instance — call through it so `this` stays bound to the original object:

```ts
const src = config.log;
const diag: ResolvedParamStoreLogger = {
  info: (obj, msg) => { src?.info?.(obj, msg); },
  warn: (obj, msg) => { src?.warn?.(obj, msg); },
  debug: (obj, msg) => { src?.debug?.(obj, msg); },
  error: (obj, msg) => { src?.error?.(obj, msg); }
};
```

Additionally, `routes/provision.js`'s `GET /:name` handler should catch a param-store failure and return a proper error response instead of letting an unhandled throw 500 the request.

## Open question / follow-up

Once the logger no longer crashes, the *real* param-store refresh failure will finally be observable — the `eyevinn-app-config-svc` instance backing `ovctest` is confirmed healthy/running, so this is most likely an auth/API-key or request-shape issue in the param-store client itself, not the parameter-store service being down. That needs a second look once logging is fixed and the actual error message is visible; filing separately if it turns out to be independent.

## Reproduction

1. Hit any endpoint on `ovctest` that resolves the workspace stack (`/ui`, `/api/v1/profiles`, `/api/v1/assets`, `/api/v1/provision`, etc.)
2. Observe `stack resolver: parameter-store refresh failed; serving fallback resolution` with `fallback: "in-memory (no object storage)"` on every single request
3. `GET /api/v1/provision/ovctest` → `500 this[writeSym] is not a function`

**Comment by birme** [comment]
Broken down into sub-issues: #438, #439, #440, #441. Closing this in favor of those.
