### ISSUE TITLE
fix: bind stack-resolver diagnostic logger so param-store failures log instead of crashing

### ISSUE THREAD

**Issue by birme** [Eyevinn/open-videocore#438]
## Summary
In `src/services/param-store.ts` (introduced by #431 / #433), the diagnostic logger is built by spreading a live pino logger instance:

```ts
const diag: ResolvedParamStoreLogger = { ...NOOP_DIAG_LOG, ...config.log };
```

Spreading copies pino's per-level methods as detached function references. Pino's internal `LOG` depends on `this[writeSym]`, which only exists on the real instance, so every `diag.error/warn/debug/info` call throws `TypeError: this[writeSym] is not a function` instead of logging. This masks the real param-store refresh failure and cascades into the fallbacks described in #437.

## Fix
Call through the source logger so `this` stays bound rather than spreading it:

```ts
const src = config.log;
const diag: ResolvedParamStoreLogger = {
  info: (obj, msg) => { src?.info?.(obj, msg); },
  warn: (obj, msg) => { src?.warn?.(obj, msg); },
  debug: (obj, msg) => { src?.debug?.(obj, msg); },
  error: (obj, msg) => { src?.error?.(obj, msg); }
};
```

## Acceptance criteria
- Confirm the exact `ResolvedParamStoreLogger` shape and `config.log` type in `src/services/param-store.ts` before editing (fetch the real symbol; do not assume).
- `withRetry` in `param-store.ts` no longer throws from the logger on a param-store failure; the underlying error is logged with its original object/message.
- No remaining spread of a pino/logger instance in the param-store diagnostic path.

## Scope
Logger binding only. Route error handling, the regression test, and the underlying param-store failure investigation are tracked separately.

Split out from #437.
